/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paulh
 */
public class Interface_Cadenas extends javax.swing.JFrame {
    
    private int k=0;
    private int l=0;
    private int j=0;
    private int m=0;
    private int z=0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_Cadenas.class.getName());

    /**
     * Creates new form Interface_Cadenas
     */
    public Interface_Cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        Bt_bas1 = new javax.swing.JButton();
        Bt_bas2 = new javax.swing.JButton();
        Bt_bas3 = new javax.swing.JButton();
        Bt_bas4 = new javax.swing.JButton();
        Bt_haut1 = new javax.swing.JButton();
        Bt_haut2 = new javax.swing.JButton();
        Bt_haut3 = new javax.swing.JButton();
        Bt_haut4 = new javax.swing.JButton();
        Numero1 = new javax.swing.JLabel();
        Numero2 = new javax.swing.JLabel();
        Numero3 = new javax.swing.JLabel();
        Numero4 = new javax.swing.JLabel();
        Instruction = new javax.swing.JLabel();
        Bt_test = new javax.swing.JButton();
        Bt_recommence = new javax.swing.JButton();
        Nb_tentetive = new javax.swing.JLabel();
        Nb_num_exact = new javax.swing.JLabel();
        Nb_num_haut = new javax.swing.JLabel();
        Nb_num_bas = new javax.swing.JLabel();
        nb_bon = new javax.swing.JLabel();
        nb_haut = new javax.swing.JLabel();
        nb_bas = new javax.swing.JLabel();
        Tentative = new javax.swing.JLabel();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_bas1.setText("\\/");
        Bt_bas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_bas1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_bas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 210, 70, -1));

        Bt_bas2.setText("\\/");
        Bt_bas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_bas2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_bas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, -1));

        Bt_bas3.setText("\\/");
        Bt_bas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_bas3ActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_bas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, -1));

        Bt_bas4.setText("\\/");
        Bt_bas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_bas4ActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_bas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));

        Bt_haut1.setText("/\\");
            Bt_haut1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Bt_haut1ActionPerformed(evt);
                }
            });
            getContentPane().add(Bt_haut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

            Bt_haut2.setText("/\\");
                Bt_haut2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Bt_haut2ActionPerformed(evt);
                    }
                });
                getContentPane().add(Bt_haut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, -1));

                Bt_haut3.setText("/\\");
                    Bt_haut3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            Bt_haut3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(Bt_haut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, -1));

                    Bt_haut4.setText("/\\");
                        Bt_haut4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Bt_haut4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(Bt_haut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 70, -1));

                        Numero1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        Numero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Numero1.setText("0");
                        Numero1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
                        Numero1.setInheritsPopupMenu(false);
                        Numero1.setMaximumSize(new java.awt.Dimension(46, 22));
                        Numero1.addContainerListener(new java.awt.event.ContainerAdapter() {
                            public void componentAdded(java.awt.event.ContainerEvent evt) {
                                Numero1ComponentAdded(evt);
                            }
                        });
                        getContentPane().add(Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 72, 111));

                        Numero2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        Numero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Numero2.setText("0");
                        Numero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 72, 111));

                        Numero3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        Numero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Numero3.setText("0");
                        Numero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(Numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 72, 111));

                        Numero4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        Numero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Numero4.setText("0");
                        Numero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(Numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 72, 111));

                        Instruction.setText("Trouver le bon code en moins de 5 tentatives !");
                        getContentPane().add(Instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 24, 330, -1));

                        Bt_test.setText("TESTER");
                        Bt_test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Bt_testActionPerformed(evt);
                            }
                        });
                        getContentPane().add(Bt_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

                        Bt_recommence.setText("RECOMMENCER");
                        Bt_recommence.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Bt_recommenceActionPerformed(evt);
                            }
                        });
                        getContentPane().add(Bt_recommence, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

                        Nb_tentetive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        Nb_tentetive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Nb_tentetive.setText("0");
                        Nb_tentetive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(Nb_tentetive, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 81, 50));

                        Nb_num_exact.setText("Nombre de chiffres exacts :");
                        getContentPane().add(Nb_num_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 156, -1));

                        Nb_num_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(Nb_num_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, -1));

                        Nb_num_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(Nb_num_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 156, -1));

                        nb_bon.setText("jLabel10");
                        getContentPane().add(nb_bon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 43, -1));

                        nb_haut.setText("jLabel11");
                        getContentPane().add(nb_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 43, -1));

                        nb_bas.setText("jLabel12");
                        getContentPane().add(nb_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 43, -1));

                        Tentative.setText("TENTATIVES");
                        getContentPane().add(Tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 70, 20));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void Bt_bas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_bas3ActionPerformed
        // TODO add your handling code here:
        j--;
        Numero3.setText(""+j);
        if(j<1){
            j=10;
        }
    }//GEN-LAST:event_Bt_bas3ActionPerformed

    private void Bt_haut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_haut1ActionPerformed
        // TODO add your handling code here:
        k++;
        Numero1.setText(""+k);
        if(k>8){
            k=-1;
        }
    }//GEN-LAST:event_Bt_haut1ActionPerformed

    private void Bt_recommenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_recommenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_recommenceActionPerformed

    private void Bt_haut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_haut2ActionPerformed
        // TODO add your handling code here:
        l++;
        Numero2.setText(""+l);
        if(l>8){
            l=-1;
        }
    }//GEN-LAST:event_Bt_haut2ActionPerformed

    private void Bt_haut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_haut3ActionPerformed
        // TODO add your handling code here:
        j++;
        Numero3.setText(""+j);
        if(j>8){
            j=-1;
        }
    }//GEN-LAST:event_Bt_haut3ActionPerformed

    private void Bt_haut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_haut4ActionPerformed
        // TODO add your handling code here:
        m++;
        Numero4.setText(""+m);
        if(m>8){
            m=-1;
        }
    }//GEN-LAST:event_Bt_haut4ActionPerformed

    private void Bt_bas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_bas1ActionPerformed
        // TODO add your handling code here:
        k--;
        Numero1.setText(""+k);
        if(k<1){
            k=10;
        }
    }//GEN-LAST:event_Bt_bas1ActionPerformed

    private void Bt_bas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_bas2ActionPerformed
        // TODO add your handling code here:
        l--;
        Numero2.setText(""+l);
        if(l<1){
            l=10;
        }
    }//GEN-LAST:event_Bt_bas2ActionPerformed

    private void Bt_bas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_bas4ActionPerformed
        // TODO add your handling code here:
        m--;
        Numero4.setText(""+m);
        if(m<1){
            m=10;
        }
    }//GEN-LAST:event_Bt_bas4ActionPerformed

    private void Numero1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Numero1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero1ComponentAdded

    private void Bt_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_testActionPerformed
        // TODO add your handling code here:
        z++;
        Nb_tentetive.setText(""+z);
    }//GEN-LAST:event_Bt_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface_Cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_bas1;
    private javax.swing.JButton Bt_bas2;
    private javax.swing.JButton Bt_bas3;
    private javax.swing.JButton Bt_bas4;
    private javax.swing.JButton Bt_haut1;
    private javax.swing.JButton Bt_haut2;
    private javax.swing.JButton Bt_haut3;
    private javax.swing.JButton Bt_haut4;
    private javax.swing.JButton Bt_recommence;
    private javax.swing.JButton Bt_test;
    private javax.swing.JLabel Instruction;
    private javax.swing.JLabel Nb_num_bas;
    private javax.swing.JLabel Nb_num_exact;
    private javax.swing.JLabel Nb_num_haut;
    private javax.swing.JLabel Nb_tentetive;
    private javax.swing.JLabel Numero1;
    private javax.swing.JLabel Numero2;
    private javax.swing.JLabel Numero3;
    private javax.swing.JLabel Numero4;
    private javax.swing.JLabel Tentative;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel nb_bas;
    private javax.swing.JLabel nb_bon;
    private javax.swing.JLabel nb_haut;
    // End of variables declaration//GEN-END:variables
}
